version: '3'

services:

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data #MacOSの場合
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    restart: always

  frontend:
    build:
      context: miso_frontend
    volumes:
      - ./miso_frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
